name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Create users.csv file for authentication
      - name: Create users.csv
        run: |
          echo "username,password" > users.csv
          echo "admin,password123" >> users.csv
          echo "user2,password123" >> users.csv

      # Run JMeter test with PerfAction
      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v5.6.3
        with:
          test-plan-path: './Restful-booker.jmx'
          args: '-l Restful_Booker.jtl -e -o dashboard -Jjmeter.reportgenerator.overall_granularity=100'

      # Upload JTL results
      - name: Upload JTL Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: Restful_Booker.jtl
